#!/bin/bash

# JX2 Paysys Help Script
# Shows available commands and usage

echo "🎮 JX2 Paysys - Available Commands"
echo "=================================="
echo ""
echo "📦 Build & Development:"
echo "   ./build.sh       - Build all binaries (Linux static)"
echo "   ./clean.sh       - Remove build artifacts"
echo "   ./clean.sh --full - Remove artifacts + Go cache"
echo ""
echo "🚀 Running:"
echo "   ./start.sh       - Build and run server"
echo "   ./run.sh         - Run server (build first)"
echo ""
echo "🧪 Testing:"
echo "   ./test.sh        - Run protocol tests"
echo ""
echo "📚 Documentation:"
echo "   ./help.sh        - Show this help"
echo ""
echo "📁 Generated Files:"
echo "   paysys-linux-bin - Main payment server"
echo "   test-linux       - Protocol test utility"
echo "   client-linux     - Test client (if available)"
echo ""
echo "⚙️  Configuration:"
echo "   paysys.ini       - Server configuration file"
echo "   jx2_paysys.sql   - Database schema"
echo ""
echo "💡 Quick Start:"
echo "   1. ./build.sh    # Build binaries"
echo "   2. ./run.sh      # Start server"
echo "   3. ./test.sh     # Test in another terminal"